### ISSUE TITLE
Windows 10 x64 - NameError: name 'blue' is not defined

### ISSUE THREAD

**Issue by ANTONIOPSD** [xf97/BiAn#1]
This is the error I get when trying on a temp contract.

```
C:\Users\Administrator\Desktop\Solidity\BiAn-master\src>python main.py temp.sol temp.sol_json.ast
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Solidity\BiAn-master\src\main.py", line 41, in <module>
    %s''' % (blue, end))
NameError: name 'blue' is not defined
```

**Comment by Murf** [comment]
if machine.lower().startswith(('os', 'win', 'darwin', 'ios')):
    colors = **True** # Colors shouldn't be displayed in mac & windows

Change False to True here is a quick fix, you have to do it in a few files.

**Comment by ANTONIOPSD** [comment]
That worked, thanks.
